%YAML:1.0

#common parameters
imu_topic: "/mtuav/imu0"
image_topic: "/frontfpv_color"
output_path: "/home/nnplvio_ws/src/nn-pl-vio/Trajactory"         # vins outputs will be wrttento vins_folder_path + output_path

#camera calibration
model_type: KANNALA_BRANDT
camera_name: camera
image_width: 1920
image_height: 1080
projection_parameters:
  k2: -0.017784451980575697
  k3: -0.0029481698662521378
  k4: 0.0084894141750293754
  k5: -0.014614037956088028
  mu: 799.51049194946381
  mv: 800.07894531866941
  u0: 978.17617339331969
  v0: 536.35715207978092

# Extrinsic parameter between IMU and Camera.
estimate_extrinsic: 0   # 0  Have an accurate extrinsic parameters. We will trust the following imu^R_cam, imu^T_cam, don't change it.
                        # 1  Have an initial guess about extrinsic parameters. We will optimize around your initial guess.
                        # 2  Don't know anything about extrinsic parameters. You don't need to give R,T. We will try to calibrate it. Do some rotation movement at beginning. 
ex_calib_result_path: "/config/euroc/ex_calib_result.yaml"  # If you choose 1 or 2, the extrinsic calibration result will be written vins_folder_path + ex_calib_result_path.                        
#If you choose 0 or 1, you should write down the following matrix.
#Rotation from camera frame to imu frame, imu^R_cam
extrinsicRotation: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [-4.3702846354810206e-03, 3.2580385793912155e-02,
       9.9945956350105780e-01, 9.9956384618936500e-01,
       -2.9048919058188939e-02, 5.3176773759394634e-03,
       2.9206471942510977e-02, 9.9904688516759366e-01,
       -3.2439223689858590e-02]
#Translation from camera frame to imu frame, imu^T_cam
extrinsicTranslation: !!opencv-matrix
   rows: 3
   cols: 1
   dt: d
   data: [1.9931455518723648e-01, 2.3453999248180223e-03,
       -8.8550028720317964e-03]

#feature traker paprameters
max_cnt: 500            # max feature number in feature tracking
min_dist: 30            # min distance between two features 
freq: 10                # frequence (Hz) of publish tracking result. At least 10Hz for good estimation. If set 0, the frequence will be same as raw image 
F_threshold: 1.0        # ransac threshold (pixel)
show_track: 1           # publish tracking image as topic
equalize: 1             # if image is too dark or light, trun on equalize to find enough features
fisheye: 0              # if using fisheye, trun on it. A circle mask will be loaded to remove edge noisy points

#optimization parameters
max_solver_time: 0.06  # max solver itration time (ms), to guarantee real time
max_num_iterations: 10   # max solver itrations, to guarantee real time
keyframe_parallax: 10.0 # keyframe selection threshold (pixel)

#imu parameters       The more accurate parameters you provide, the better performance
# acc_n: 0.2          # accelerometer measurement noise standard deviation. #0.2
# gyr_n: 0.02         # gyroscope measurement noise standard deviation.     #0.05
# acc_w: 0.0002         # accelerometer bias random work noise standard deviation.  #0.02
# gyr_w: 2.0e-5       # gyroscope bias random work noise standard deviation.     #4.0e-5
# g_norm: 9.81007     # gravity magnitude
acc_n: 0.08          # accelerometer measurement noise standard deviation. #0.2   0.04
gyr_n: 0.004         # gyroscope measurement noise standard deviation.     #0.05  0.004
acc_w: 0.00004         # accelerometer bias random work noise standard deviation.  #0.02
gyr_w: 2.0e-6       # gyroscope bias random work noise standard deviation.     #4.0e-5
g_norm: 9.81007     # gravity magnitude

#loop closure parameters
loop_closure: 1   #if you want to use loop closure to minimize the drift, set loop_closure true and give your brief pattern file path and vocabulary file path accordingly;
                     #also give the camera calibration file same as feature_tracker node
load_previous_pose_graph: 1 
fast_relocalization: 0 
pose_graph_save_path: "/home/plus/Work/plvins_ws/src/PL-VINS/Trajactory/posegraph/" # save and load path


pattern_file: "/support_files/brief_pattern.yml"
voc_file: "/support_files/brief_k10L6.bin"
min_loop_num: 25


