%YAML:1.0

#common parameters
imu_topic: "/mtuav/imu0"
image_topic: "/mtuav/stereo_down0/image_raw"
output_path: "/home/nnplvio_ws/src/nn-pl-vio/Trajactory"         # vins outputs will be wrttento vins_folder_path + output_path

#camera calibration 
model_type: PINHOLE
camera_name: camera
image_width: 1280
image_height: 800
distortion_parameters:
   k1: 8.4479988187990004e-02
   k2: -8.2715949932212887e-02
   p1: 9.2522968667606312e+02
   p2: 3.9723800223006913e+02
projection_parameters:
   fx: 9.2544856424722730e+02
   fy: 6.1276180358215265e+02
   cx: 3.630e+02
   cy: 2.481e+02
# Extrinsic parameter between IMU and Camera.
estimate_extrinsic: 0   # 0  Have an accurate extrinsic parameters. We will trust the following imu^R_cam, imu^T_cam, don't change it.
                        # 1  Have an initial guess about extrinsic parameters. We will optimize around your initial guess.
                        # 2  Don't know anything about extrinsic parameters. You don't need to give R,T. We will try to calibrate it. Do some rotation movement at beginning. 
ex_calib_result_path: "/config/euroc/ex_calib_result.yaml"  # If you choose 1 or 2, the extrinsic calibration result will be written vins_folder_path + ex_calib_result_path.                        
#If you choose 0 or 1, you should write down the following matrix.
#Rotation from camera frame to imu frame, imu^R_cam
extrinsicRotation: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ -1.1838863047585803e-02, -9.9963138811089214e-01,
       2.4432135093593314e-02, 9.9992556749146910e-01,
       -1.1763199192274934e-02, 3.2383053633755817e-03,
       -2.9497116137195706e-03, 2.4468654402192799e-02,
       9.9969624594330753e-01 ]
#Translation from camera frame to imu frame, imu^T_cam
extrinsicTranslation: !!opencv-matrix
   rows: 3
   cols: 1
   dt: d
   data: [ 1.6503049003590153e-01, -5.5096161230278551e-02,
       1.2688860399124469e-01 ]

#feature traker paprameters
max_cnt: 500            # max feature number in feature tracking
min_dist: 30            # min distance between two features 
freq: 10                # frequence (Hz) of publish tracking result. At least 10Hz for good estimation. If set 0, the frequence will be same as raw image 
F_threshold: 1.0        # ransac threshold (pixel)
show_track: 1           # publish tracking image as topic
equalize: 1             # if image is too dark or light, trun on equalize to find enough features
fisheye: 0              # if using fisheye, trun on it. A circle mask will be loaded to remove edge noisy points

#optimization parameters
max_solver_time: 0.06  # max solver itration time (ms), to guarantee real time
max_num_iterations: 8   # max solver itrations, to guarantee real time
keyframe_parallax: 10.0 # keyframe selection threshold (pixel)

#imu parameters       The more accurate parameters you provide, the better performance
# acc_n: 0.2          # accelerometer measurement noise standard deviation. #0.2
# gyr_n: 0.02         # gyroscope measurement noise standard deviation.     #0.05
# acc_w: 0.0002         # accelerometer bias random work noise standard deviation.  #0.02
# gyr_w: 2.0e-5       # gyroscope bias random work noise standard deviation.     #4.0e-5
# g_norm: 9.81007     # gravity magnitude
acc_n: 0.08          # accelerometer measurement noise standard deviation. #0.2   0.04
gyr_n: 0.004         # gyroscope measurement noise standard deviation.     #0.05  0.004
acc_w: 0.00004         # accelerometer bias random work noise standard deviation.  #0.02
gyr_w: 2.0e-6       # gyroscope bias random work noise standard deviation.     #4.0e-5
g_norm: 9.81007     # gravity magnitude

#loop closure parameters
loop_closure: 1   #if you want to use loop closure to minimize the drift, set loop_closure true and give your brief pattern file path and vocabulary file path accordingly;
                     #also give the camera calibration file same as feature_tracker node
load_previous_pose_graph: 1 
fast_relocalization: 0 
pose_graph_save_path: "/home/nnplvio_ws/src/nn-pl-vio/Trajactory/posegraph/" # save and load path


pattern_file: "/support_files/brief_pattern.yml"
voc_file: "/support_files/brief_k10L6.bin"
min_loop_num: 25

